### ISSUE TITLE
Extension not working.

### ISSUE THREAD

**Issue by irsyadpage** [CRBroughton/htmx-attributes#1]
I tried to use the htmx-attributes extension. But, I get the following error:

![aa](https://github.com/CRBroughton/htmx-attributes/assets/14093866/84a035ab-e132-4e90-ac06-7a5c93b75179)

I use HTMX on Go (via [Templ](https://github.com/a-h/templ)). Am I misconfiguring something? I tested in ubuntu and windows, both produce similar error.

**Comment by CRBroughton** [comment]
Hi there! 

Thank you for opening up this issue. I've created a test extension for you; Could you please try this extension out by manually installing it, to see if the issue goes away? If this corrects your issue, I can publish a new version with this fix.

https://github.com/CRBroughton/htmx-attributes/releases/tag/astro-fix

**Comment by CRBroughton** [comment]
Also, could I ask if the extension (the previous version without this fix), if it works for you despite this error, or does the error block usage of the extension?

**Comment by irsyadpage** [comment]
Tested on:
- `v0.3.0` > No runtime error
- `v0.4.0` > Similar runtime error as `v0.5.0`
- `v0.5.0-astro-fix` > The error is fixed

All tested versions are functioning despite the runtime error.

Thank you for the swift fixed 👍.

**Comment by CRBroughton** [comment]
My pleasure, and thank you for the prompt replies and well :)

I don't foresee much change to HTMX's API, so that extension should be good for you for quite a while. As the runtime error wasn't effecting your usage of the extension, I'll keep the Astro language support in 0.5.0, as well as future version, as it will help those that use Astro.

If it does start effecting usage, I could split out Astro support into it's own extension.

I'll leave the astro-less version available on the releases page so it's also available, should you require it in the future.

Thank you again for the support on the extension! If you do have any future issues related to this, feel free to re-open this issue and I can take a look at splitting out the Astro support.
